# build terraform infrastructure
name: Build and Deploy Terraform Infrastructure
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        run: terraform  init

      - name: Terraform Plan
        run: terraform plan 

      - name: Terraform Apply
        if:  
        run: terraform apply -auto-approve 

      - name: Output Terraform State
        run: terraform output -json
