# build terraform infrastructure
name: Build and Deploy Terraform Infrastructure
on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: latest

      - name: Terraform Init
        run: terraform  init

      - name: Terraform Plan
        env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENAT_ID: ${{ secrets.AZURE_TENANT_ID }}
      run: terraform plan -var="client_id=${{ secrets.AZURE_CLIENT_ID }}" \
                          -var="client_secret=${{ secrets.AZURE_CLIENT_SECRET }}" \
                          --var="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" \
                          -var="tenant_id=${{ secrets.AZURE_TENANT_ID }}" 
      

        
        run: terraform plan 

      - name: Terraform Apply
        if:  
        run: terraform apply -auto-approve 

      - name: Output Terraform State
        run: terraform output -json
