name: Deploy Azure infra with Terraform

on:
 push:
  branches:
     -main

jobs:
  terraform:
     runs-on: ubuntu-latest

env:
ARM_CLIENT_ID
ARM_CLIENT_SECRET
ARM_SUBSCRIPTION_ID =
ARM_TENANT_ID = 0b889ca3-c111-47fc-b0ed-88a37593b8fa

Steps:
 -name: checkout repo
  uses: actions/checkout@3
  
- name: Setup Terraform
  uses: hashicorp/setup-terraform@v3
  with:
    terraform_version: 1.6.6

- name: Terraform Init
  run: terraform init

-name: Terraform Validate
 run: Terraform Validate 

-name: Terraform Plan
 run: terraform Plan

-name: Terrafrom Apply
 run: terraform apply -auto-approve

    
